name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths: ./starter/frontend/*

  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend

env:
  NODE_VER: '18.14'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from the repository. 
      uses: actions/checkout@v3

    - name: Set up a Node.js environment using the specified node version 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}

    - name: Install the dependencies.
      run: pipenv install

    - name: Run the linter.
      run: pipenv run lint

  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code from the repository. 
      uses: actions/checkout@v4

    - name: Set up a Node.js environment using the specified node version and cache dependencies
      uses: actions/setup-node@v3
      with:
         node-version: ${{ env.NODE_VER }}

    - name: Install the dependencies.
      run: pipenv install

    - name: Run the tests
      run: pipenv run test
  
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from the repository. 
      uses: actions/checkout@v4

    - name: Set up a Node.js environment using the specified node version and cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}

    - name: Install the dependencies.
      run: pipenv install
        
    - name: Run the test
      run: pipenv run test
