name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths: ./starter/frontend/*

  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend

env:
  PYTHON_VER: '3.10.6'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from the repository. 
      uses: actions/checkout@v3

    - name: Set up a python environment using the specified version 
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VER }}

    - name: Install pipenv
      run: pip install pipenv
       
    - name: Install dependencies
      run: pipenv install --dev

    - name: Run the linter.
      run: pipenv run lint

  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code from the repository. 
      uses: actions/checkout@v4

    - name: Set up a python environment using the specified version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VER }}
    
    - name: Install pipenv
      run:  pip install pipenv

    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pipenv install --dev

    - name: Run the tests
      run: pipenv run test
  
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from the repository. 
      uses: actions/checkout@v4

    - name: Set up a python environment using the specified version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VER }}

    - name: Install pipenv
      run: pip install pipenv

    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pipenv install --dev

    - name: Run the tests
      run: pipenv run test

    
